import { resolveEndTurn, validateEndTurn } from './endTurn';
import { resolveMove, validateMove } from './move';
import type { Command, EndTurnCommand, GameEvent, GameState, MoveCommand, PlayerId } from './types';

declare const validated: unique symbol;

/**
 * The mark of a command that has been authenticated *and* checked.
 *
 * `validated` is a `unique symbol` that is never exported, so this property is
 * unwritable outside this module. An Action can therefore only come from
 * `validateCommand` -- forging one, or reviving one from JSON, does not compile.
 */
interface Validated {
  actor: PlayerId;
  readonly [validated]: true;
}

export type MoveAction = MoveCommand & Validated;
export type EndTurnAction = EndTurnCommand & Validated;

/**
 * A command the authority has accepted: authenticated, legal, and ready to
 * resolve. Not "a command with an actor attached" -- if it can still be
 * refused, it is not an Action yet.
 */
export type Action = MoveAction | EndTurnAction;

export type ValidationResult = { ok: true; action: Action } | { ok: false; reason: string };

/**
 * The only constructor of an Action, and the only place legality is decided.
 *
 * This is what invariant 5 became: rather than each reducer remembering to
 * check its own input, an unchecked action is unrepresentable, so resolution
 * cannot happen without validation having happened first. The compiler
 * enforces the ordering that a convention used to.
 */
export function validateCommand(
  state: GameState,
  command: Command,
  actor: PlayerId,
): ValidationResult {
  // Sender identity first: everything below assumes the actor is allowed to be
  // giving orders at all.
  if (actor !== state.currentTurn) return { ok: false, reason: 'not your turn' };

  const reason = refuse(state, command);
  if (reason) return { ok: false, reason };

  // The single cast in the codebase that mints the brand.
  return { ok: true, action: { ...command, actor } as Action };
}

function refuse(state: GameState, command: Command): string | null {
  switch (command.type) {
    case 'move':
      return validateMove(state, command);
    case 'endTurn':
      return validateEndTurn();
    default:
      // Unreachable given the types, but commands arrive as JSON over a wire
      // where types guarantee nothing. parseCommand should have caught this;
      // refusing again costs a line and removes the assumption.
      return `unknown command type: ${String((command as Command).type)}`;
  }
}

/**
 * What actually happened. Callable only with a validated Action, so it does no
 * legality checking of its own -- that already happened, provably.
 *
 * Returns events rather than state: `applyEvents` is the only mutator. Dice
 * will arrive here as an argument, generated by the server, keeping this pure.
 */
export function resolveAction(state: GameState, action: Action): GameEvent[] {
  switch (action.type) {
    case 'move':
      return resolveMove(action);
    case 'endTurn':
      return resolveEndTurn(state);
    default:
      throw new Error(`unknown action type: ${String((action as Action).type)}`);
  }
}
